name: Mondoo Policy Upload
on:
  push:
    paths:
    - 'policy/luna-rad-baseline.yml'
jobs:
  mondoo-policy-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mondoohq/actions/policy@scottford/refactor-actions
      with:
        service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        args: validate
        path: policy/luna-rad-baseline.yml
    - uses: mondoohq/actions/policy@scottford/refactor-actions
      with:
        service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
        args: add -f
        path: policy/luna-rad-baseline.yml 